import { Image, Pressable, StyleSheet, View } from 'react-native'
import * as Linking from 'expo-linking'
import Text from './Text'
import { compactNumber } from '../utils/format'
import theme from '../theme'
const Stat = ({ value, label }) => <View style={styles.stat}><Text fontWeight="bold">{compactNumber(value)}</Text><Text color="secondary">{label}</Text></View>
export default function RepositoryItem({ repository, showLink = false, onPress }) {
  return <Pressable onPress={onPress} style={styles.container}><View style={styles.heading}><Image style={styles.avatar} source={{ uri: repository.ownerAvatarUrl }} /><View style={styles.headingText}><Text fontSize="subheading" fontWeight="bold">{repository.fullName}</Text><Text color="secondary" style={styles.description}>{repository.description}</Text><Text style={styles.language}>{repository.language}</Text></View></View><View style={styles.stats}><Stat value={repository.stargazersCount} label="Stars" /><Stat value={repository.forksCount} label="Forks" /><Stat value={repository.reviewCount} label="Reviews" /><Stat value={repository.ratingAverage} label="Rating" /></View>{showLink && <Pressable style={styles.link} onPress={() => Linking.openURL(repository.url)}><Text style={styles.linkText} fontWeight="bold">Open in GitHub</Text></Pressable>}</Pressable>
}
const styles = StyleSheet.create({ container: { backgroundColor: theme.colors.surface, padding: 16 }, heading: { flexDirection: 'row' }, avatar: { width: 50, height: 50, borderRadius: 10 }, headingText: { flex: 1, marginLeft: 14 }, description: { marginTop: 5, lineHeight: 20 }, language: { alignSelf: 'flex-start', color: 'white', backgroundColor: theme.colors.primary, borderRadius: 4, paddingHorizontal: 8, paddingVertical: 5, marginTop: 9, overflow: 'hidden' }, stats: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 18 }, stat: { alignItems: 'center', gap: 3 }, link: { backgroundColor: theme.colors.primary, borderRadius: 7, padding: 13, alignItems: 'center', marginTop: 16 }, linkText: { color: 'white' } })
